### ISSUE TITLE
Load Gliner Model locally

### ISSUE THREAD

**Issue by rishabh208gupta** [theirstory/gliner-spacy#11]
Hi, I have been trying to use the gliner-spacy library to do basic ner on some documents. I really appreciate how easy it is to integrate with spacy. I am facing one issue that the first document takes a long time to process, I am guessing because the model gets downloaded first. The subsequent documents process fairly quicker. Is there is a way to load and save the model locally beforehand?

**Comment by wjbmattingly** [comment]
Thanks so much for the kind words about the package! Hmm. After you have processed the first document and then rerun all the documents (in a separate instance of the same environment) is the delay the same? You have the ability to load the model first with GliNER which will download it if it is not available in the environment. Once in the environment, it should load that model instantly from the environment local model after that, since GliNER saves it for you.

**Comment by rishabh208gupta** [comment]
@wjbmattingly the delay in the first document was indeed due to model being downloaded. By initiating it with GliNER, there is no longer any delay. Thanks!
