### ISSUE TITLE
Support for other languages 

### ISSUE THREAD

**Issue by AIMads** [theirstory/gliner-spacy#5]
Hey is it possible to change nlp pipeline initilisation with another language for example Danish with "da"?

**Comment by wjbmattingly** [comment]
Thanks for the comment! It should work natively for any language. You can use whichever blank pipeline you want, or spin up any spaCy model. There are several Danish models available from spaCy. I recommend disabling the ner or placing the gliner-spacy pipe before ner so that you can prioritize the gliner-spacy output.
